### ISSUE TITLE
Investigate why dpad is flipped around on Wii U Pro controller

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/TitanOne#10]
Up and down appear to be reversed when used on Xbox One (PS4 seems fine).

**Comment by J2Kbr** [comment]
Hi Pablo, I am testing this (Switch Pro controller on Xbox One) and the dpad up/down is working as expected (not inverted). Not sure why you got the inverted functions for the up/down, Please re-check with the latest firmware (to be release yet today) and if the problem persist re-open this issue. thanks.
